### ISSUE TITLE
Can't run 'jovo run --watch' using 'npm run dev'

### ISSUE THREAD

**Issue by rv-ekramer** [jovotech/jovo-framework-nodejs#112] opened 2018-03-30 19:06 UTC
I've tried adding a dev script to my package.json file to alias `jovo run --watch` to `npm run dev` but it never works. Every single time I get the following error.
![screen shot 2018-03-30 at 3 04 37 pm](https://user-images.githubusercontent.com/31253814/38150172-b53166a0-342b-11e8-9fb8-5b31c7ad3fce.png)

And here's the log file the screenshot it referencing:

```
/Users/ekramer/.npm/_logs/2018-03-30T19_04_35_339Z-debug.log 0 info it worked if it ends with ok
1 verbose cli [ '/Users/ekramer/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/Users/ekramer/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.7.1
3 info using node@v8.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle tv-helper@1.0.0~predev: tv-helper@1.0.0
6 info lifecycle tv-helper@1.0.0~dev: tv-helper@1.0.0
7 verbose lifecycle tv-helper@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle tv-helper@1.0.0~dev: PATH: /Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ekramer/Desktop/voice-assistants/tv-helper/node_modules/.bin:/Users/ekramer/.nvm/versions/node/v8.9.4/bin:/usr/share/www/intranet.directstartv.com/scripts/srcsync-dir:/usr/local/bin:/usr/share/www/devops/scripts:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/share/www/intranet.directstartv.com/scripts/srcsync-dir:/usr/share/www/devops/scripts:/usr/local/sbin
9 verbose lifecycle tv-helper@1.0.0~dev: CWD: /Users/ekramer/Desktop/voice-assistants/tv-helper
10 silly lifecycle tv-helper@1.0.0~dev: Args: [ '-c', 'jovo run --watch' ]
11 silly lifecycle tv-helper@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle tv-helper@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: tv-helper@1.0.0 dev: `jovo run --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid tv-helper@1.0.0
15 verbose cwd /Users/ekramer/Desktop/voice-assistants/tv-helper
16 verbose Darwin 16.7.0
17 verbose argv "/Users/ekramer/.nvm/versions/node/v8.9.4/bin/node" "/Users/ekramer/.nvm/versions/node/v8.9.4/bin/npm" "run" "dev"
18 verbose node v8.9.4
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error tv-helper@1.0.0 dev: `jovo run --watch`
22 error Exit status 1
23 error Failed at the tv-helper@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

The weird part is if I run `jovo run --watch` normally without aliasing it to `npm run dev` it works....

**Comment by rv-ekramer** [comment] 2018-03-30 19:57
I just created a new skill using jovo cli version `1.0.10` and putting `jovo run --watch` as a dev script in the package json worked. But ideally I'd like to be on v1.0.4 of jovo-framework, or, even better `1.1.1` because of the custom logging methods that were added as a result of #85 

package.json of the new skill i just created

package.json for the new project

```json
{
  "name": "jovo-sample-voice-app-nodejs",
  "version": "1.0.0",
  "description": "A sample voice app that works with the Jovo framework",
  "main": "index.js",
  "dependencies": {
    "jovo-framework": "^1.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "dev": "jovo run --watch"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jovotech/jovo-sample-voice-app-nodejs.git"
  },
  "author": "Jovo",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/jovotech/jovo-sample-voice-app-nodejs/issues"
  },
  "homepage": "https://github.com/jovotech/jovo-sample-voice-app-nodejs#readme"
}
```

package.json for the "old" project I already had created

```json
{
  "name": "tv-helper",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "jovo run --watch"
  },
  "dependencies": {
    "array-shuffle": "^1.0.1",
    "aws-sdk": "^2.210.0",
    "axios": "^0.18.0",
    "body-parser": "^1.18.2",
    "cross-env": "^5.1.4",
    "express": "^4.16.2",
    "jovo-framework": "^1.0.4",
    "node-fetch": "^2.0.0"
  },
  "devDependencies": {
    "jovo-cli": "^1.0.9",
    "nodemon": "^1.17.1"
  },
  "author": "Red Ventures"
}
```

**Comment by jankoenig** [comment] 2018-03-30 20:00
If you update the newly created project to `1.1.1` with `npm install jovo-framework`, does it still work then?

**Comment by rv-ekramer** [comment] 2018-03-30 20:11
So running `npm install --save jovo-framework` in the new skill still works. But here's the problem. The "old" skill is under version control. It's using an enterprise Atlassian Stash account that my company pays for. How would I set up the git to push any new changes in the new skill to our repo? would it pull down all our branches? Would others on my team be able to pull down these changes without problem? 

It seems like a pretty big ask, to expect users to blow away their ENTIRE project and copy everything over everytime `jovo-framework` randomly breaks. As `1.1.1` or a future version might eventually do. 

Would you guys be able to look into whats causing the issues referenced in #111 when trying to upgrade existing projects created using an older version of `jovo-cli` to newer version of `jovo-framework`

**Comment by jankoenig** [comment] 2018-03-30 20:58
This is not an ask to blow away your project, just meant to debug to see if the problem has to do with the framework or could be an internal bug in your project.

**Comment by jankoenig** [comment] 2018-03-30 21:15
We will investigate this feature further, but please keep in mind it's 11pm here + it's a holiday in Germany,  so patience is appreciated

**Comment by aswetlow** [comment] 2018-03-31 07:54
Tested on Windows and Ubuntu on Windows. Can't reproduce the error. 
Does something like this work?
``` 
"scripts": {
    "dev": "node -v"
  },
```
``` 
"scripts": {
    "dev": "jovo -v"
  },
```

**Comment by rv-ekramer** [comment] 2018-04-03 16:32
Thank you guys for all your help! I didn't know you were in Germany, I'm sorry to keep you guys up so late.

**Comment by rv-ekramer** [comment] 2018-04-03 16:32
@aswetlow I'll try it and let you know.

**Comment by rv-ekramer** [comment] 2018-04-04 16:39
@aswetlow both of the below work

```json
"scripts": {
    "dev": "node -v"
 },
```

```json
"scripts": {
    "dev": "jovo -v"
 },
```

Even this works:

```json
"scripts": {
    "dev": "jovo run"
 },
```

But not this:

```json
"scripts": {
    "dev": "jovo run --watch"
 },
```

Which leads me to believe its a problem with `nodemon`

**Comment by rv-ekramer** [comment] 2018-04-04 16:50
@aswetlow  **Update: ** After uninstalling `jovo-cli` globally with `npm uninstall -g jovo-cli` in an attempt to fix my issue in #111. Upon reinstallation, now, when I run `jovo run --watch` independently of the package.json i get the same error I get when trying to run the command from `dev` script.

```bash
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/jovo-cli/node_modules/nodemon/bin/nodemon.js ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Which leads me to think the issue described in this ticket is a general issue with the watch command inside the jovo cli

**Comment by jankoenig** [comment] 2018-04-05 11:17
Hi @rv-ekramer, which operating system are you using?

**Comment by rv-ekramer** [comment] 2018-04-05 13:37
@jankoenig macOS 10.12.6

**Comment by aswetlow** [comment] 2018-04-05 14:50
Is ```nodemon.js``` in this folder?
/Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/jovo-cli/node_modules/nodemon/bin ?
Looks like the nodemon installation failed.

**Comment by rv-ekramer** [comment] 2018-04-09 14:45
It is. See? 

<img width="1404" alt="screen shot 2018-04-09 at 10 02 11 am" src="https://user-images.githubusercontent.com/31253814/38504539-f013fa58-3be2-11e8-8258-4739b0d23c26.png">

I just removed the node_modules folder inside of my project as well as jovo and nodemon globally and reinstalled, but `jovo run --watch` still doesn't seem to be working either when ran as a part of `npm run dev` or by itself

**Comment by aswetlow** [comment] 2018-04-10 15:56
Are you sure it's the ```/Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/jovo-cli/node_modules/nodemon/bin``` folder?

The files in your screenshot look more like they are from the global node\bin folder: ```/Users/ekramer/.nvm/versions/node/v8.9.4/bin```

In ```jovo run --watch``` we're looking explicitly for the nodemon installation (nodemon.js) in the node_modules/nodemon folder of the jovo cli. 

Where's the jovo cli located? ```which jovo```

**Comment by trevorwang** [comment] 2018-04-11 02:10
I also met this issue. But I use below instead.

```
  "devDependencies": {
    "nodemon": "1.17.2"
  },
  "scripts": {
    "dev": "./node_modules/.bin/nodemon index.js -e js --webhook"
  },
```

**Comment by rv-ekramer** [comment] 2018-04-11 17:31
@trevorwang When doing that my skill says "Connection Error: Your jovo webhook endpoint is not running. Please run 'jovo run'"

**Comment by rv-ekramer** [comment] 2018-04-11 17:37
@aswetlow you're right. Look? I just found out that nodemon was infact at `/Users/ekramer/.nvm/versions/node/v8.9.4/bin/nodemon` and not at `/Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/jovo-cli/node_modules/nodemon/bin`

Currently nodemon doesn't exist at all at /Users/ekramer/.nvm/versions/node/v8.9.4/lib/node_modules/jovo-cli/node_modules.

How would i get it there? Is that the whole problem?
<img width="951" alt="screen shot 2018-04-11 at 1 35 51 pm" src="https://user-images.githubusercontent.com/31253814/38633389-7cea3d88-3d8d-11e8-9824-e6bd8c942fb9.png">

**Comment by jankoenig** [comment] 2018-05-17 17:04
Hey @rv-ekramer, this should be resolved with the newest version of our CLI (thanks to @fgnass https://github.com/jovotech/jovo-cli/pull/16). Closing this, but if you keep running into problems, please let us know! Thanks

**Closed by jankoenig** 2018-05-17 17:04 UTC
